CREATE FUNCTION refined_domain_uuid(seed text) RETURNS uuid AS $$
DECLARE
    hash text := md5('refined-domain:' || seed);
BEGIN
    RETURN (substr(hash,1,8) || '-' || substr(hash,9,4) || '-5' || substr(hash,14,3) || '-a' || substr(hash,18,3) || '-' || substr(hash,21,12))::uuid;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

CREATE TEMP TABLE refined_domains (
    subject_code text NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    sort_order integer NOT NULL,
    PRIMARY KEY (subject_code,code)
) ON COMMIT DROP;

INSERT INTO refined_domains VALUES
-- Mathematics, primary school.
('MATH','MATH_PRI_NUMBER_OPERATIONS','数与运算','整数、数位、四则运算与运算顺序',110),
('MATH','MATH_PRI_FRACTION_RATIO','小数、分数与比例','小数、分数、百分数、因数倍数、比与比例',120),
('MATH','MATH_PRI_ALGEBRA_RELATIONS','数量关系与代数','用未知数和等量关系表达实际问题',130),
('MATH','MATH_PRI_MEASUREMENT','测量','单位换算、长度时间质量、周长、面积与体积',140),
('MATH','MATH_PRI_GEOMETRY','图形与位置','角、平面图形、位置与方向',150),
('MATH','MATH_PRI_DATA_MODELING','统计、概率与建模','平均数、统计图表、概率直觉与应用建模',160),
-- Mathematics, junior secondary.
('MATH','MATH_JUN_RATIONAL_NUMBERS','有理数与数轴','正负数、数轴、相反数、绝对值与有理数运算',210),
('MATH','MATH_JUN_EXPRESSIONS_OPERATIONS','代数式与整式','代数式、整式、同类项、乘法公式、因式分解、分式与根式',220),
('MATH','MATH_JUN_EQUATIONS_INEQUALITIES','方程与不等式','一元一次方程、二元一次方程组与不等式',230),
('MATH','MATH_JUN_COORDINATE_GEOMETRY','坐标与几何','坐标系、三角形、全等、对称、勾股定理与平行四边形',240),
('MATH','MATH_JUN_FUNCTIONS','函数','函数概念与一次函数',250),
('MATH','MATH_JUN_DATA_ANALYSIS','数据分析','数据整理、统计分析与折扣数据应用',260),

-- Chinese, primary school.
('CHINESE','CHI_PRI_LANGUAGE','字词句与积累','字词、句子理解与语言积累',110),
('CHINESE','CHI_PRI_READING','阅读理解','段落、主旨、信息、人物事件与因果关系',120),
('CHINESE','CHI_PRI_EXPRESSION','表达与写作','复述、写话与作文基础',130),
('CHINESE','CHI_PRI_POETRY_CULTURE','古诗与传统文化','古诗基础与传统文化',140),
-- Chinese, junior secondary.
('CHINESE','CHI_JUN_MODERN_READING','现代文阅读','记叙文、说明文、议论文以及信息与证据分析',210),
('CHINESE','CHI_JUN_LANGUAGE','语言运用','修辞、句段作用与综合语言运用',220),
('CHINESE','CHI_JUN_WRITING','写作','初中写作表达与修改',230),
('CHINESE','CHI_JUN_CLASSICAL','文言文与古诗词','文言文、古诗词及意象理解',240),
('CHINESE','CHI_JUN_EXTENDED_READING','名著与整本书阅读','名著阅读与整本书理解',250),

-- English, primary school.
('ENGLISH','ENG_PRI_FOUNDATION','语音、词汇与语法基础','Phonics、常用词汇与基础时态',110),
('ENGLISH','ENG_PRI_COMMUNICATION','听说与日常交流','听读与日常句型',120),
('ENGLISH','ENG_PRI_READING_EXPRESSION','阅读与表达','简短阅读与简单表达',130),
-- English, junior secondary.
('ENGLISH','ENG_JUN_VOCAB_GRAMMAR','词汇与语法','词汇、语法以及常见句型',210),
('ENGLISH','ENG_JUN_TENSE_CLAUSE','时态与从句','时态体系、从句基础与一般现在时',220),
('ENGLISH','ENG_JUN_READING_CLOZE','阅读与完形','阅读理解、细节定位与完形思维',230),
('ENGLISH','ENG_JUN_DISCOURSE','语篇理解','语篇结构、衔接与整体理解',240),
('ENGLISH','ENG_JUN_COMMUNICATION','听说、交流与写作','日常交流、听说与写作',250),

-- Physics, junior secondary.
('PHYSICS','PHY_JUN_MOTION','测量与机械运动','测量、机械运动与速度',210),
('PHYSICS','PHY_JUN_SOUND','声学','声音的产生、传播与应用',220),
('PHYSICS','PHY_JUN_OPTICS','光学','光现象与透镜',230),
('PHYSICS','PHY_JUN_MATTER','质量与密度','质量、密度与物质属性',240),
('PHYSICS','PHY_JUN_THERMAL','热学','温度、热量与内能现象',250),
('PHYSICS','PHY_JUN_MECHANICS','力与机械','力与运动、压强浮力、功、机械能和简单机械',260),
('PHYSICS','PHY_JUN_ELECTRICITY','电学','电流、电压、电阻、欧姆定律、电功率与家庭电路',270),
('PHYSICS','PHY_JUN_MAGNETISM','磁学','磁现象及其应用',280),

-- Chemistry, junior secondary.
('CHEMISTRY','CHEM_JUN_FOUNDATION','化学入门与实验','物质变化、实验基本操作与观察证据',210),
('CHEMISTRY','CHEM_JUN_AIR_WATER','空气、氧气与水','空气组成、氧气性质与水',220),
('CHEMISTRY','CHEM_JUN_MICRO_SYMBOLS','微观粒子与化学用语','分子原子、元素、化学式与化合价',230),
('CHEMISTRY','CHEM_JUN_REACTION_LAWS','化学反应与方程式','质量守恒与化学方程式',240),
('CHEMISTRY','CHEM_JUN_CARBON_COMBUSTION','碳与燃烧','碳及其化合物与燃烧条件',250),
('CHEMISTRY','CHEM_JUN_MATERIALS','金属与酸碱盐','金属、酸、碱、盐及其性质',260),
('CHEMISTRY','CHEM_JUN_SOLUTION_LIFE','溶液、浓度与生活化学','溶液、浓度和化学与生活',270);

INSERT INTO domains (id,subject_id,code,name,description,sort_order)
SELECT refined_domain_uuid(seed.subject_code || ':' || seed.code),subject.id,
       seed.code,seed.name,seed.description,seed.sort_order
FROM refined_domains seed
JOIN subjects subject ON subject.code=seed.subject_code;

CREATE TEMP TABLE unit_domain_mapping (
    unit_code text PRIMARY KEY,
    domain_code text NOT NULL
) ON COMMIT DROP;

INSERT INTO unit_domain_mapping VALUES
-- Mathematics.
('PRIMARY_WHOLE_NUMBERS','MATH_PRI_NUMBER_OPERATIONS'),
('PRIMARY_DECIMALS_FRACTIONS','MATH_PRI_FRACTION_RATIO'),
('PRIMARY_FACTORS_RATIOS','MATH_PRI_FRACTION_RATIO'),
('PRIMARY_EQUATIONS','MATH_PRI_ALGEBRA_RELATIONS'),
('PRIMARY_MEASUREMENT','MATH_PRI_MEASUREMENT'),
('PRIMARY_PLANE_MEASUREMENT','MATH_PRI_MEASUREMENT'),
('PRIMARY_SOLID_MEASUREMENT','MATH_PRI_MEASUREMENT'),
('PRIMARY_GEOMETRY','MATH_PRI_GEOMETRY'),
('PRIMARY_STATISTICS','MATH_PRI_DATA_MODELING'),
('PRIMARY_APPLICATION_MODELING','MATH_PRI_DATA_MODELING'),
('JUNIOR_SECONDARY_SIGNED_NUMBERS','MATH_JUN_RATIONAL_NUMBERS'),
('JUNIOR_SECONDARY_ALGEBRAIC_EXPRESSIONS','MATH_JUN_EXPRESSIONS_OPERATIONS'),
('JUNIOR_SECONDARY_ALGEBRAIC_OPERATIONS','MATH_JUN_EXPRESSIONS_OPERATIONS'),
('JUNIOR_SECONDARY_EQUATIONS_INEQUALITIES','MATH_JUN_EQUATIONS_INEQUALITIES'),
('JUNIOR_SECONDARY_COORDINATES','MATH_JUN_COORDINATE_GEOMETRY'),
('JUNIOR_SECONDARY_TRIANGLES','MATH_JUN_COORDINATE_GEOMETRY'),
('JUNIOR_SECONDARY_GEOMETRIC_RELATIONS','MATH_JUN_COORDINATE_GEOMETRY'),
('JUNIOR_SECONDARY_FUNCTIONS','MATH_JUN_FUNCTIONS'),
('JUNIOR_SECONDARY_DATA_ANALYSIS','MATH_JUN_DATA_ANALYSIS'),
-- Chinese.
('PRIMARY_WORDS_SENTENCES','CHI_PRI_LANGUAGE'),
('PRIMARY_BASIC_READING','CHI_PRI_READING'),
('PRIMARY_NARRATIVE_READING','CHI_PRI_READING'),
('PRIMARY_EXPRESSION_WRITING','CHI_PRI_EXPRESSION'),
('PRIMARY_CLASSICAL_CULTURE','CHI_PRI_POETRY_CULTURE'),
('JUNIOR_SECONDARY_READING_GENRES','CHI_JUN_MODERN_READING'),
('JUNIOR_SECONDARY_EVIDENCE_ANALYSIS','CHI_JUN_MODERN_READING'),
('JUNIOR_SECONDARY_LANGUAGE_ART','CHI_JUN_LANGUAGE'),
('JUNIOR_SECONDARY_WRITING','CHI_JUN_WRITING'),
('JUNIOR_SECONDARY_CLASSICAL_TEXT','CHI_JUN_CLASSICAL'),
('JUNIOR_SECONDARY_EXTENDED_READING','CHI_JUN_EXTENDED_READING'),
-- English.
('PRIMARY_FOUNDATION','ENG_PRI_FOUNDATION'),
('PRIMARY_EVERYDAY_COMMUNICATION','ENG_PRI_COMMUNICATION'),
('PRIMARY_READING_EXPRESSION','ENG_PRI_READING_EXPRESSION'),
('JUNIOR_SECONDARY_VOCABULARY_GRAMMAR','ENG_JUN_VOCAB_GRAMMAR'),
('JUNIOR_SECONDARY_TENSES_CLAUSES','ENG_JUN_TENSE_CLAUSE'),
('JUNIOR_SECONDARY_READING_COMPREHENSION','ENG_JUN_READING_CLOZE'),
('JUNIOR_SECONDARY_DISCOURSE','ENG_JUN_DISCOURSE'),
('JUNIOR_SECONDARY_WRITING_COMMUNICATION','ENG_JUN_COMMUNICATION'),
('JUNIOR_SECONDARY_LISTENING_SPEAKING','ENG_JUN_COMMUNICATION'),
-- Physics.
('JUNIOR_SECONDARY_MEASUREMENT_MOTION','PHY_JUN_MOTION'),
('JUNIOR_SECONDARY_SOUND','PHY_JUN_SOUND'),
('JUNIOR_SECONDARY_OPTICS','PHY_JUN_OPTICS'),
('JUNIOR_SECONDARY_MASS_DENSITY','PHY_JUN_MATTER'),
('JUNIOR_SECONDARY_THERMAL','PHY_JUN_THERMAL'),
('JUNIOR_SECONDARY_FORCE_MOTION','PHY_JUN_MECHANICS'),
('JUNIOR_SECONDARY_PRESSURE_BUOYANCY','PHY_JUN_MECHANICS'),
('JUNIOR_SECONDARY_WORK_MACHINES','PHY_JUN_MECHANICS'),
('JUNIOR_SECONDARY_BASIC_CIRCUITS','PHY_JUN_ELECTRICITY'),
('JUNIOR_SECONDARY_CIRCUIT_LAWS','PHY_JUN_ELECTRICITY'),
('JUNIOR_SECONDARY_MAGNETISM','PHY_JUN_MAGNETISM'),
-- Chemistry.
('JUNIOR_SECONDARY_FOUNDATIONS','CHEM_JUN_FOUNDATION'),
('JUNIOR_SECONDARY_COMMON_SUBSTANCES','CHEM_JUN_AIR_WATER'),
('JUNIOR_SECONDARY_MICRO_WORLD','CHEM_JUN_MICRO_SYMBOLS'),
('JUNIOR_SECONDARY_CHEMICAL_LANGUAGE','CHEM_JUN_MICRO_SYMBOLS'),
('JUNIOR_SECONDARY_REACTION_LAWS','CHEM_JUN_REACTION_LAWS'),
('JUNIOR_SECONDARY_CARBON_COMBUSTION','CHEM_JUN_CARBON_COMBUSTION'),
('JUNIOR_SECONDARY_MATERIALS','CHEM_JUN_MATERIALS'),
('JUNIOR_SECONDARY_SOLUTIONS','CHEM_JUN_SOLUTION_LIFE'),
('JUNIOR_SECONDARY_CHEMISTRY_LIFE','CHEM_JUN_SOLUTION_LIFE');

UPDATE units unit
SET domain_id=domain.id
FROM unit_domain_mapping mapping
JOIN domains domain ON domain.code=mapping.domain_code
WHERE unit.code=mapping.unit_code;

UPDATE knowledge_points knowledge_point
SET domain_id=unit.domain_id,updated_at=now()
FROM units unit
WHERE knowledge_point.unit_id=unit.id;

DELETE FROM domains domain
WHERE domain.code IN (
    'PRIMARY_NUMBER_ALGEBRA','PRIMARY_MEASUREMENT_GEOMETRY','PRIMARY_DATA_MODELING',
    'JUNIOR_NUMBER_ALGEBRA','JUNIOR_GEOMETRY','JUNIOR_FUNCTION_DATA',
    'PRIMARY_LANGUAGE_FOUNDATION','PRIMARY_READING','PRIMARY_EXPRESSION_CULTURE',
    'JUNIOR_MODERN_READING','JUNIOR_LANGUAGE_EXPRESSION','JUNIOR_CLASSICS',
    'PRIMARY_COMMUNICATION_LITERACY','JUNIOR_LANGUAGE_KNOWLEDGE',
    'JUNIOR_COMPREHENSION','JUNIOR_COMMUNICATION','MEASUREMENT_MOTION',
    'WAVES_OPTICS','MATTER_THERMAL','MECHANICS','ELECTRICITY_MAGNETISM',
    'EXPERIMENT_MATTER','MICRO_SYMBOLS','LAWS_REACTIONS','CHEMISTRY_APPLICATION'
)
AND NOT EXISTS (SELECT 1 FROM units unit WHERE unit.domain_id=domain.id);

DROP FUNCTION refined_domain_uuid(text);
